In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('..')

import numpy as np
from collections import Counter
from sklearn.metrics import accuracy_score

# Load Toy Dataset

In [3]:
from sklearn.datasets import load_diabetes

tmp = load_diabetes()
fn = np.vectorize(lambda x: 0 if x < 99 else 2 if x > 182 else 1)
y = fn(tmp.target)
X = tmp.data

print(Counter(y))

Counter({2: 149, 1: 148, 0: 145})


# Example

In [4]:
from pipelinetweak.pipe import ProbT
from sklearn.linear_model import LogisticRegression

trans = ProbT(LogisticRegression(solver='lbfgs', multi_class='multinomial'), drop=False)
trans.fit(X, y)
Z = trans.transform(X)

print(Z)

[[0.24432975 0.33879065 0.41687959]
 [0.53187749 0.31741405 0.15070845]
 [0.2857872  0.35339299 0.3608198 ]
 ...
 [0.34960776 0.36286038 0.28753185]
 [0.23947523 0.33564868 0.42487608]
 [0.54081725 0.30239429 0.15678847]]
